# Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements; and to You under the Apache License, Version 2.0.
name: Empty Workflow
on:
  workflow_dispatch:

jobs:
  empty_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Echo
        run: echo
