name: 'Tests: node.js >=0.12.0 <10'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@b82215040d0711e3252126c08551315008964c4f
    with:
      range: '>=0.12.0 <10'
      type: minors
      command: npm run tests-only

  node:
    name: node >= 0.12
    needs: [tests]
    runs-on: ubuntu-22.04
    steps:
      - run: echo tests completed
